---
title: 'EEOB563 -- Assignment #3'
author: "Dennis Psaroudakis"
date: "February 20th 2019"
output:
  pdf_document:
    dev: pdf
    latex_engine: lualatex
    md_extensions: +link_attributes+multiline_tables
    pandoc_args: --listings
mainfontoptions: Numbers=OldStyle
monofont: Linux Libertine Mono O
mainfont: Linux Libertine O
papersize: letter
sansfont: Linux Biolinum O
language: en-US
titlepage: true
...

## 3
c) I did an alltree search on the sequences and this is the result

```
Exhaustive search settings:
  Optimality criterion = parsimony
    Character-status summary:
      Of 30 total characters:
        All characters are of type 'unord'
        All characters have equal weight
        22 characters are constant (proportion = 0.733333)
        6 variable characters are parsimony-uninformative
        Number of parsimony-informative characters = 2
    Gaps are treated as "missing"
  Initial 'Maxtrees' setting = 100
  Branches collapsed (creating polytomies) if maximum branch length is zero
  'MulTrees' option in effect
  No topological constraints in effect
  Trees are unrooted

Exhaustive search completed:
  Number of trees evaluated = 2027025
  Score of best tree found = 11
  Score of worst tree found = 16
  Number of trees retained = 3
  Time used = 0.54 sec (CPU time = 0.54 sec)
```
So the best score is 11, according to PAUP. I don't know why it is so different from my score, but I guess it just uses a different algorithm and/or different values in the algorithm. The best tree it found looks like this:

```
Tree 3 (rooted using default outgroup)

Tree length = 11
Consistency index (CI) = 1.0000
Homoplasy index (HI) = 0.0000
CI excluding uninformative characters = 1.0000
HI excluding uninformative characters = 0.0000
Retention index (RI) = 1.0000
Rescaled consistency index (RC) = 1.0000

/----------------------------------------------------------------------------------------------------------------------------------------- Dolphin
|
|                                                          /--------------------------------------- Hippopotamus
|                                                          |
|                                                          |                                      /--------------------------------------- Cow
|                   /-------------------------------------13                                      |
|                   |                                      +-------------------------------------11--------------------------------------- Giraffe
|                   |                                      |                                      |
|                   |                                     12                                      \--------------------------------------- Goat
|                   |                                      |
|                   |                                      \--------------------------------------- Sheep
|                   |
\------------------14 Camel
                    |
                    + Sperm whale
                    |
                    + Blue whale
                    |
                    \ Pig
```
Please look at my [paup log](https://github.com/Thyra/EEOB563/blob/master/assignments/3/3c.log) file for additional info, here is also the [FASTA file](https://github.com/Thyra/EEOB563/blob/master/assignments/3/3.fa) I wrote and the [Nexus file](https://github.com/Thyra/EEOB563/blob/master/assignments/3/3.nxs) I generated from it.

# Part II
I aligned the sequences with Pal2Nal (vertebrate table, output format FASTA, I told it to remove gaps, otherwise elephant and human were shorter than the others. Otherwise I left the standard options), I got a lot of warnings that I does not correspond to ATA but it seems like it worked ([result file](https://github.com/Thyra/EEOB563/blob/master/assignments/3/cob_aligned.fa)). I converted it into a [Nexus file](https://github.com/Thyra/EEOB563/blob/master/assignments/3/cob_aligned.nxs).

## 4
Please look at the complete log file of the analysis [here](https://github.com/Thyra/EEOB563/blob/master/assignments/3/4.log). All the trees that were found had a very similar score and only marginally different topologie, the run with 100 reps was the most different from the rest. It reminds me of the trees I did by hand where I also found the best tree very early. So either this is just the global optimum and very easy to find or it is a local optimum and none of the methods were thorough enough to find the global optimum.

## 5



